### ISSUE TITLE
Blueprint Compilation Errors for Material Generator

### ISSUE THREAD

**Issue by sean-fisher** [ACaesuraIsStillMusic/UE4-Swappable-Materials#1]
Material Generator widget blueprints have many compilation errors due to unrecognized function calls. All of these have to do with asset management, so maybe there's a plugin or something I am missing? This is from a clean clone of the repository with no additional materials downloaded. I tried compiling on UE4 Version 4.22, 4.23, and a source build.
![image](https://user-images.githubusercontent.com/22086579/70285309-164e0800-1795-11ea-9b9c-2331238c8a2f.png)

(Thanks for sharing all these materials, BTW!)

**Comment by ACaesuraIsStillMusic** [comment]
Check to see if the editor scripting plugin and python scripting plugins
are installed
Looks like they are missing from your project file

**Comment by sean-fisher** [comment]
Yep, it was the python plugin that I needed. It isn't listed as a necessary plugin in the uproject file so I wasn't sure what I was missing. Thanks!
